// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.25;

import {TranscriptLib} from "../src/TranscriptLib.sol";

/// @title TranscriptCompatTest
/// @notice E2E transcript compatibility test: Rust prove → Solidity verify.
///         These test vectors are generated by the Rust transcript and MUST
///         be reproduced exactly by the Solidity transcript.
///         Any mismatch breaks Fiat-Shamir binding.
contract TranscriptCompatTest {
    uint256 constant P = 0xFFFFFFFF00000001;

    // ═══════════════════════════════════════════════════════════════════════
    //  Rust-generated test vectors (canonical Goldilocks field elements)
    // ═══════════════════════════════════════════════════════════════════════

    uint256 constant V1_EMPTY_SQUEEZE           = 5564066233726241458;
    uint256 constant V2_ABSORB_42               = 5382117256048105213;
    uint256 constant V3_ABSORB_VEC_123          = 5153944257736891297;
    uint256 constant V4_DOMAIN_SEP_99           = 9437712998329239873;
    uint256 constant V5_ABSORB_BYTES_DEADBEEF   = 6431216113529961845;
    uint256 constant V6_SQUEEZE1                = 12336020981118610616;
    uint256 constant V6_SQUEEZE2                = 16787817580992291001;
    uint256 constant V6_SQUEEZE3                = 1575619615394496293;
    uint256 constant V7_BATCH_R                 = 13000817457220507840;
    uint256 constant V7_BETA                    = 7330374892527880894;
    uint256 constant V7_GAMMA                   = 15545281684134560778;
    uint256 constant V7_ALPHA                   = 9387608023261396568;

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 1: Fresh transcript, squeeze immediately
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector1_empty_squeeze() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        uint256 c = TranscriptLib.squeezeChallenge(t);
        require(c == V1_EMPTY_SQUEEZE, string.concat(
            "V1 mismatch: got ", _uint2str(c), " expected ", _uint2str(V1_EMPTY_SQUEEZE)
        ));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 2: Absorb single field element
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector2_absorb_42() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        TranscriptLib.absorbField(t, 42);
        uint256 c = TranscriptLib.squeezeChallenge(t);
        require(c == V2_ABSORB_42, string.concat(
            "V2 mismatch: got ", _uint2str(c), " expected ", _uint2str(V2_ABSORB_42)
        ));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 3: Absorb field vec [1, 2, 3]
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector3_absorb_vec_123() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        uint256[] memory vals = new uint256[](3);
        vals[0] = 1; vals[1] = 2; vals[2] = 3;
        TranscriptLib.absorbFieldVec(t, vals);
        uint256 c = TranscriptLib.squeezeChallenge(t);
        require(c == V3_ABSORB_VEC_123, string.concat(
            "V3 mismatch: got ", _uint2str(c), " expected ", _uint2str(V3_ABSORB_VEC_123)
        ));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 4: Domain separation + absorb
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector4_domain_sep_99() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        TranscriptLib.domainSeparate(t, "test-label");
        TranscriptLib.absorbField(t, 99);
        uint256 c = TranscriptLib.squeezeChallenge(t);
        require(c == V4_DOMAIN_SEP_99, string.concat(
            "V4 mismatch: got ", _uint2str(c), " expected ", _uint2str(V4_DOMAIN_SEP_99)
        ));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 5: Absorb raw bytes
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector5_absorb_bytes() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        bytes memory data = new bytes(4);
        data[0] = 0xDE; data[1] = 0xAD; data[2] = 0xBE; data[3] = 0xEF;
        TranscriptLib.absorbBytes(t, data);
        uint256 c = TranscriptLib.squeezeChallenge(t);
        require(c == V5_ABSORB_BYTES_DEADBEEF, string.concat(
            "V5 mismatch: got ", _uint2str(c), " expected ", _uint2str(V5_ABSORB_BYTES_DEADBEEF)
        ));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 6: Multiple squeezes
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector6_multiple_squeezes() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);
        TranscriptLib.absorbField(t, 12345);
        uint256 c1 = TranscriptLib.squeezeChallenge(t);
        uint256 c2 = TranscriptLib.squeezeChallenge(t);
        uint256 c3 = TranscriptLib.squeezeChallenge(t);
        require(c1 == V6_SQUEEZE1, string.concat("V6.1 mismatch: got ", _uint2str(c1)));
        require(c2 == V6_SQUEEZE2, string.concat("V6.2 mismatch: got ", _uint2str(c2)));
        require(c3 == V6_SQUEEZE3, string.concat("V6.3 mismatch: got ", _uint2str(c3)));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Test Vector 7: Full protocol flow
    // ═══════════════════════════════════════════════════════════════════════

    function test_vector7_protocol_flow() external pure {
        TranscriptLib.Transcript memory t;
        TranscriptLib.init(t);

        TranscriptLib.domainSeparate(t, "circuit");
        uint256[] memory pubInputs = new uint256[](1);
        pubInputs[0] = 21;
        TranscriptLib.absorbFieldVec(t, pubInputs);

        TranscriptLib.domainSeparate(t, "batch-commit");
        uint256 batchR = TranscriptLib.squeezeChallenge(t);
        require(batchR == V7_BATCH_R, string.concat("V7.batch_r mismatch: got ", _uint2str(batchR)));

        // Absorb fake commitment root (32 bytes of 0xAA)
        bytes memory commitment = new bytes(32);
        for (uint256 i = 0; i < 32; i++) commitment[i] = 0xAA;
        TranscriptLib.absorbBytes(t, commitment);

        TranscriptLib.domainSeparate(t, "challenges");
        uint256 beta = TranscriptLib.squeezeChallenge(t);
        uint256 gamma = TranscriptLib.squeezeChallenge(t);
        uint256 alpha = TranscriptLib.squeezeChallenge(t);

        require(beta == V7_BETA, string.concat("V7.beta mismatch: got ", _uint2str(beta)));
        require(gamma == V7_GAMMA, string.concat("V7.gamma mismatch: got ", _uint2str(gamma)));
        require(alpha == V7_ALPHA, string.concat("V7.alpha mismatch: got ", _uint2str(alpha)));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Helper: uint to string for error messages
    // ═══════════════════════════════════════════════════════════════════════

    function _uint2str(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "0";
        uint256 temp = v;
        uint256 digits;
        while (temp > 0) { digits++; temp /= 10; }
        bytes memory buffer = new bytes(digits);
        while (v > 0) {
            digits--;
            buffer[digits] = bytes1(uint8(48 + v % 10));
            v /= 10;
        }
        return string(buffer);
    }
}
