// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";

/// @title WhirVerifyTest
/// @notice Tests WHIR verification using fixtures generated by the Rust prover.
///         Uses split-commit mode (numCommitments=2) for preprocessed + witness vectors.
///         Run: forge test -vvv --match-contract WhirVerifyTest
contract WhirVerifyTest is Test {

    /// @notice Test WHIR verification of a small circuit (degree_bits=2).
    function test_whir_small_mul() public view {
        string memory json = vm.readFile("test/fixtures/small_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a medium circuit (degree_bits=3).
    function test_whir_medium_mul() public view {
        string memory json = vm.readFile("test/fixtures/medium_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a large circuit (degree_bits=4).
    function test_whir_large_mul() public view {
        string memory json = vm.readFile("test/fixtures/large_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a Poseidon hash circuit (degree_bits=2).
    function test_whir_poseidon_hash() public view {
        string memory json = vm.readFile("test/fixtures/poseidon_hash.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a recursive circuit (degree_bits=11).
    function test_whir_recursive_verify() public view {
        string memory json = vm.readFile("test/fixtures/recursive_verify.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification with degree_bits=13 / numRounds=2.
    /// This exercises the intermediate round code path in SpongefishWhirVerify.
    function test_whir_huge_mul() public view {
        string memory json = vm.readFile("test/fixtures/huge_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test that a tampered WHIR transcript fails verification.
    function test_whir_tampered_transcript_fails() public {
        string memory json = vm.readFile("test/fixtures/small_mul.json");

        // Parse the WHIR data (unified transcript)
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        // Build evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);

        // Build WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);

        // Tamper with transcript (flip a byte in the middle)
        uint256 mid = transcript.length / 2;
        transcript[mid] = bytes1(uint8(transcript[mid]) ^ 0xFF);

        // Verification should fail
        bool success;
        try this.externalVerifyWhir(protocolId, sessionId, transcript, hints, evaluations, params) returns (bool result) {
            success = result;
        } catch {
            success = false;
        }
        assertFalse(success, "Tampered transcript should fail WHIR verification");
    }

    /// @notice External wrapper for try/catch (Solidity requires external calls for try).
    function externalVerifyWhir(
        bytes memory protocolId,
        bytes memory sessionId,
        bytes memory transcript,
        bytes memory hints,
        GoldilocksExt3.Ext3[] memory evaluations,
        SpongefishWhirVerify.WhirParams memory params
    ) external pure returns (bool) {
        return SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, "", transcript, hints, evaluations, params
        );
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Internal: parse fixture JSON and verify WHIR proof
    // ═══════════════════════════════════════════════════════════════════════

    function _verifyWhirFromFixture(string memory json) internal view {
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        console.log("WHIR transcript length:", transcript.length);
        console.log("WHIR hints length:", hints.length);
        console.log("Protocol ID length:", protocolId.length);

        // Parse evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);
        console.log("Evaluation[0] c0:", evaluations[0].c0);

        // Parse WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);
        console.log("WHIR numVariables:", params.numVariables);
        console.log("WHIR foldingFactor:", params.foldingFactor);
        console.log("WHIR numRounds:", params.numRounds);
        console.log("WHIR numCommitments:", params.numCommitments);

        // Verify
        uint256 gasBefore = gasleft();
        bool valid = SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, "", transcript, hints, evaluations, params
        );
        uint256 gasUsed = gasBefore - gasleft();
        console.log("WHIR verification gas:", gasUsed);

        assertTrue(valid, "WHIR verification should pass");
    }

    function _parseEvaluations(string memory json) internal pure returns (GoldilocksExt3.Ext3[] memory) {
        // Split-commit: 2 evaluations (preprocessed + witness)
        GoldilocksExt3.Ext3[] memory evals = new GoldilocksExt3.Ext3[](2);

        uint64 p0 = uint64(vm.parseUint(vm.parseJsonString(json, ".preprocessedWhirEval.c0")));
        uint64 p1 = uint64(vm.parseUint(vm.parseJsonString(json, ".preprocessedWhirEval.c1")));
        uint64 p2 = uint64(vm.parseUint(vm.parseJsonString(json, ".preprocessedWhirEval.c2")));
        evals[0] = GoldilocksExt3.Ext3(p0, p1, p2);

        uint64 w0 = uint64(vm.parseUint(vm.parseJsonString(json, ".witnessWhirEval.c0")));
        uint64 w1 = uint64(vm.parseUint(vm.parseJsonString(json, ".witnessWhirEval.c1")));
        uint64 w2 = uint64(vm.parseUint(vm.parseJsonString(json, ".witnessWhirEval.c2")));
        evals[1] = GoldilocksExt3.Ext3(w0, w1, w2);

        return evals;
    }

    function _parseWhirParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory) {
        SpongefishWhirVerify.WhirParams memory params;

        params.numVariables = vm.parseJsonUint(json, ".whirParams.numVariables");
        params.foldingFactor = vm.parseJsonUint(json, ".whirParams.foldingFactor");
        params.numVectors = vm.parseJsonUint(json, ".whirParams.numVectors");
        params.numCommitments = vm.parseJsonUint(json, ".whirParams.numCommitments");
        params.outDomainSamples = vm.parseJsonUint(json, ".whirParams.outDomainSamples");
        params.inDomainSamples = vm.parseJsonUint(json, ".whirParams.inDomainSamples");
        params.initialSumcheckRounds = vm.parseJsonUint(json, ".whirParams.initialSumcheckRounds");
        params.numRounds = vm.parseJsonUint(json, ".whirParams.numRounds");
        params.finalSumcheckRounds = vm.parseJsonUint(json, ".whirParams.finalSumcheckRounds");
        params.finalSize = vm.parseJsonUint(json, ".whirParams.finalSize");
        params.initialCodewordLength = vm.parseJsonUint(json, ".whirParams.initialCodewordLength");
        params.initialMerkleDepth = vm.parseJsonUint(json, ".whirParams.initialMerkleDepth");
        params.initialDomainGenerator = uint64(vm.parseJsonUint(json, ".whirParams.initialDomainGenerator"));
        params.initialInterleavingDepth = vm.parseJsonUint(json, ".whirParams.initialInterleavingDepth");
        params.initialNumVariables = vm.parseJsonUint(json, ".whirParams.initialNumVariables");
        params.initialCosetSize = vm.parseJsonUint(json, ".whirParams.initialCosetSize");
        params.initialNumCosets = vm.parseJsonUint(json, ".whirParams.initialNumCosets");

        // Parse rounds array
        uint256 numRounds = params.numRounds;
        params.rounds = new SpongefishWhirVerify.RoundParams[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".whirParams.rounds[", vm.toString(i), "]");
            params.rounds[i].codewordLength = vm.parseJsonUint(json, string.concat(prefix, ".codewordLength"));
            params.rounds[i].merkleDepth = vm.parseJsonUint(json, string.concat(prefix, ".merkleDepth"));
            params.rounds[i].domainGenerator = uint64(vm.parseJsonUint(json, string.concat(prefix, ".domainGenerator")));
            params.rounds[i].inDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".inDomainSamples"));
            params.rounds[i].outDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".outDomainSamples"));
            params.rounds[i].sumcheckRounds = vm.parseJsonUint(json, string.concat(prefix, ".sumcheckRounds"));
            params.rounds[i].interleavingDepth = vm.parseJsonUint(json, string.concat(prefix, ".interleavingDepth"));
            params.rounds[i].cosetSize = vm.parseJsonUint(json, string.concat(prefix, ".cosetSize"));
            params.rounds[i].numCosets = vm.parseJsonUint(json, string.concat(prefix, ".numCosets"));
            params.rounds[i].numVariables = vm.parseJsonUint(json, string.concat(prefix, ".numVariables"));
        }

        // Empty evaluation points → uses canonical point (1, 2, ..., n) via
        // mleEvaluateEqCanonical in SpongefishWhirVerify.
        params.evaluationPoint = new GoldilocksExt3.Ext3[](0);
        params.evaluationPoint2 = new GoldilocksExt3.Ext3[](0);

        return params;
    }
}
