// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";

/// @title WhirVerifyTest
/// @notice Tests WHIR verification using fixtures generated by the Rust prover.
///         Uses split-commit mode (numCommitments=2) for preprocessed + witness vectors.
///         Run: forge test -vvv --match-contract WhirVerifyTest
contract WhirVerifyTest is Test {

    /// @notice Test WHIR verification of a small circuit (degree_bits=2).
    function test_whir_small_mul() public view {
        string memory json = vm.readFile("test/fixtures/small_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a medium circuit (degree_bits=3).
    function test_whir_medium_mul() public view {
        string memory json = vm.readFile("test/fixtures/medium_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a large circuit (degree_bits=4).
    function test_whir_large_mul() public view {
        string memory json = vm.readFile("test/fixtures/large_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a Poseidon hash circuit (degree_bits=2).
    function test_whir_poseidon_hash() public view {
        string memory json = vm.readFile("test/fixtures/poseidon_hash.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a recursive circuit (degree_bits=11).
    function test_whir_recursive_verify() public view {
        string memory json = vm.readFile("test/fixtures/recursive_verify.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification with degree_bits=13 / numRounds=2.
    /// This exercises the intermediate round code path in SpongefishWhirVerify.
    function test_whir_huge_mul() public view {
        string memory json = vm.readFile("test/fixtures/huge_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test that a tampered WHIR transcript fails verification.
    function test_whir_tampered_transcript_fails() public {
        string memory json = vm.readFile("test/fixtures/small_mul.json");

        // Parse the WHIR data (unified transcript)
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        // Build evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);

        // Build WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);

        // Tamper with transcript (flip a byte in the middle)
        uint256 mid = transcript.length / 2;
        transcript[mid] = bytes1(uint8(transcript[mid]) ^ 0xFF);

        // Verification should fail
        bool success;
        try this.externalVerifyWhir(protocolId, sessionId, transcript, hints, evaluations, params) returns (bool result) {
            success = result;
        } catch {
            success = false;
        }
        assertFalse(success, "Tampered transcript should fail WHIR verification");
    }

    /// @notice External wrapper for try/catch (Solidity requires external calls for try).
    function externalVerifyWhir(
        bytes memory protocolId,
        bytes memory sessionId,
        bytes memory transcript,
        bytes memory hints,
        GoldilocksExt3.Ext3[] memory evaluations,
        SpongefishWhirVerify.WhirParams memory params
    ) external pure returns (bool) {
        return SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, "", transcript, hints, evaluations, params
        );
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Internal: parse fixture JSON and verify WHIR proof
    // ═══════════════════════════════════════════════════════════════════════

    function _verifyWhirFromFixture(string memory json) internal view {
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        console.log("WHIR transcript length:", transcript.length);
        console.log("WHIR hints length:", hints.length);
        console.log("Protocol ID length:", protocolId.length);

        // Parse evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);
        console.log("Evaluation[0] c0:", evaluations[0].c0);

        // Parse WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);
        console.log("WHIR numVariables:", params.numVariables);
        console.log("WHIR foldingFactor:", params.foldingFactor);
        console.log("WHIR numRounds:", params.numRounds);
        console.log("WHIR numCommitments:", params.numCommitments);

        // Verify
        uint256 gasBefore = gasleft();
        bool valid = SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, "", transcript, hints, evaluations, params
        );
        uint256 gasUsed = gasBefore - gasleft();
        console.log("WHIR verification gas:", gasUsed);

        assertTrue(valid, "WHIR verification should pass");
    }

    function _parseEvaluations(string memory json) internal pure returns (GoldilocksExt3.Ext3[] memory) {
        // Issue R2-#1: multi-point WHIR now opens at 4 points × 4 vectors = 16 evaluations.
        // Layout matches MleVerifier._runBatchAndWhir.
        GoldilocksExt3.Ext3[] memory evals = new GoldilocksExt3.Ext3[](16);

        // Point 0 (r_gate)
        evals[0] = _parseExt3Field(json, ".preprocessedWhirEval");
        evals[1] = _parseExt3Field(json, ".witnessWhirEval");
        evals[2] = _parseExt3Field(json, ".auxWhirEval");
        evals[3] = _parseExt3Field(json, ".inverseHelpersWhirEvalAtRGate");
        // Point 1 (r_inv)
        evals[4] = _parseExt3Field(json, ".preprocessedWhirEvalAtRInv");
        evals[5] = _parseExt3Field(json, ".witnessWhirEvalAtRInv");
        evals[6] = _parseExt3Field(json, ".auxWhirEvalAtRInv");
        evals[7] = _parseExt3Field(json, ".inverseHelpersWhirEvalAtRInv");
        // Point 2 (r_h)
        evals[8] = _parseExt3Field(json, ".preprocessedWhirEvalAtRH");
        evals[9] = _parseExt3Field(json, ".witnessWhirEvalAtRH");
        evals[10] = _parseExt3Field(json, ".auxWhirEvalAtRH");
        evals[11] = _parseExt3Field(json, ".inverseHelpersWhirEvalAtRH");
        // Point 3 (r_gate_v2, Issue R2-#1)
        evals[12] = _parseExt3Field(json, ".preprocessedWhirEvalAtRGateV2");
        evals[13] = _parseExt3Field(json, ".witnessWhirEvalAtRGateV2");
        evals[14] = _parseExt3Field(json, ".auxWhirEvalAtRGateV2");
        evals[15] = _parseExt3Field(json, ".inverseHelpersWhirEvalAtRGateV2");

        return evals;
    }

    function _parseExt3Field(string memory json, string memory path)
        internal pure returns (GoldilocksExt3.Ext3 memory)
    {
        return GoldilocksExt3.Ext3(
            uint64(vm.parseUint(vm.parseJsonString(json, string.concat(path, ".c0")))),
            uint64(vm.parseUint(vm.parseJsonString(json, string.concat(path, ".c1")))),
            uint64(vm.parseUint(vm.parseJsonString(json, string.concat(path, ".c2"))))
        );
    }

    /// @dev Parse a Goldilocks vector of length n from JSON string array.
    function _parseGoldilocksArray(string memory json, string memory path)
        internal pure returns (uint256[] memory out)
    {
        string[] memory strs = vm.parseJsonStringArray(json, path);
        out = new uint256[](strs.length);
        for (uint256 i = 0; i < strs.length; i++) {
            out[i] = vm.parseUint(strs[i]);
        }
    }

    function _parseWhirParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory) {
        SpongefishWhirVerify.WhirParams memory params;

        params.numVariables = vm.parseJsonUint(json, ".whirParams.numVariables");
        params.foldingFactor = vm.parseJsonUint(json, ".whirParams.foldingFactor");
        params.numVectors = vm.parseJsonUint(json, ".whirParams.numVectors");
        params.numCommitments = vm.parseJsonUint(json, ".whirParams.numCommitments");
        params.outDomainSamples = vm.parseJsonUint(json, ".whirParams.outDomainSamples");
        params.inDomainSamples = vm.parseJsonUint(json, ".whirParams.inDomainSamples");
        params.initialSumcheckRounds = vm.parseJsonUint(json, ".whirParams.initialSumcheckRounds");
        params.numRounds = vm.parseJsonUint(json, ".whirParams.numRounds");
        params.finalSumcheckRounds = vm.parseJsonUint(json, ".whirParams.finalSumcheckRounds");
        params.finalSize = vm.parseJsonUint(json, ".whirParams.finalSize");
        params.initialCodewordLength = vm.parseJsonUint(json, ".whirParams.initialCodewordLength");
        params.initialMerkleDepth = vm.parseJsonUint(json, ".whirParams.initialMerkleDepth");
        params.initialDomainGenerator = uint64(vm.parseJsonUint(json, ".whirParams.initialDomainGenerator"));
        params.initialInterleavingDepth = vm.parseJsonUint(json, ".whirParams.initialInterleavingDepth");
        params.initialNumVariables = vm.parseJsonUint(json, ".whirParams.initialNumVariables");
        params.initialCosetSize = vm.parseJsonUint(json, ".whirParams.initialCosetSize");
        params.initialNumCosets = vm.parseJsonUint(json, ".whirParams.initialNumCosets");

        // Parse rounds array
        uint256 numRounds = params.numRounds;
        params.rounds = new SpongefishWhirVerify.RoundParams[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".whirParams.rounds[", vm.toString(i), "]");
            params.rounds[i].codewordLength = vm.parseJsonUint(json, string.concat(prefix, ".codewordLength"));
            params.rounds[i].merkleDepth = vm.parseJsonUint(json, string.concat(prefix, ".merkleDepth"));
            params.rounds[i].domainGenerator = uint64(vm.parseJsonUint(json, string.concat(prefix, ".domainGenerator")));
            params.rounds[i].inDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".inDomainSamples"));
            params.rounds[i].outDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".outDomainSamples"));
            params.rounds[i].sumcheckRounds = vm.parseJsonUint(json, string.concat(prefix, ".sumcheckRounds"));
            params.rounds[i].interleavingDepth = vm.parseJsonUint(json, string.concat(prefix, ".interleavingDepth"));
            params.rounds[i].cosetSize = vm.parseJsonUint(json, string.concat(prefix, ".cosetSize"));
            params.rounds[i].numCosets = vm.parseJsonUint(json, string.concat(prefix, ".numCosets"));
            params.rounds[i].numVariables = vm.parseJsonUint(json, string.concat(prefix, ".numVariables"));
        }

        // v2 logUp multi-point WHIR — 3 evaluation points come from the
        // proof's three sumchecks (r_gate, r_inv, r_h). These are stored in
        // the fixture as Goldilocks vectors. Each entry must be embedded as
        // Ext3(x, 0, 0) before being passed to WHIR.
        params.numCommitments = 4; // override fixture (still 2 from v1)

        uint256[] memory rGate = _gatePointFromEvaluationPoint(json);
        uint256[] memory rInv = _parseGoldilocksArray(json, ".invSumcheckChallenges");
        uint256[] memory rH = _parseGoldilocksArray(json, ".hSumcheckChallenges");
        // Issue R2-#1: 4th evaluation point from the Φ_gate sumcheck output.
        uint256[] memory rGateV2 = _parseGoldilocksArray(json, ".gateSumcheckChallenges");

        params.evaluationPoint = _embedExt3(rGate);
        params.evaluationPoint2 = _embedExt3(rInv);
        params.additionalEvaluationPoints = new GoldilocksExt3.Ext3[][](2);
        params.additionalEvaluationPoints[0] = _embedExt3(rH);
        params.additionalEvaluationPoints[1] = _embedExt3(rGateV2);

        return params;
    }

    /// @dev Read sumcheck output point r_gate from the fixture's evaluationPoint
    /// (already embedded as Ext3 with c1=c2=0).
    function _gatePointFromEvaluationPoint(string memory json)
        internal pure returns (uint256[] memory out)
    {
        // Probe length by trying indices.
        uint256 len = 0;
        for (uint256 i = 0; i < 32; i++) {
            try vm.parseJsonString(json, string.concat(".evaluationPoint[", vm.toString(i), "].c0"))
                returns (string memory)
            {
                len = i + 1;
            } catch { break; }
        }
        out = new uint256[](len);
        for (uint256 i = 0; i < len; i++) {
            string memory ep = string.concat(".evaluationPoint[", vm.toString(i), "].c0");
            out[i] = vm.parseUint(vm.parseJsonString(json, ep));
        }
    }

    function _embedExt3(uint256[] memory r) internal pure returns (GoldilocksExt3.Ext3[] memory pt) {
        pt = new GoldilocksExt3.Ext3[](r.length);
        for (uint256 i = 0; i < r.length; i++) {
            pt[i] = GoldilocksExt3.Ext3(uint64(r[i]), 0, 0);
        }
    }
}
